/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ru.sarmosov.task;

import ru.sarmosov.task.entity.Purchase;
import ru.sarmosov.task.service.CountService;
import ru.sarmosov.task.service.mapper.JsonFileParser;
import ru.sarmosov.task.service.mapper.JsonFileWriter;

import java.io.IOException;
import java.time.Month;
import java.util.List;

public class Main {

    public static void main(String[] args) throws IOException {


        JsonFileParser parser = new JsonFileParser("src/main/resources/input.json");
        List<Purchase> purchaseList = parser.getListFromJson();
        List<Month> resultList = CountService.service(purchaseList);
        JsonFileWriter writer = new JsonFileWriter("src/main/resources/result.json");
        writer.writeList(resultList);

    }
}
